apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: test
spec:
  selector:
    app: mongo-deployment
  type: ClusterIP
  ports:
    - port: 27015
      targetPort: 27017
      protocol: TCP
      name: mongo-port