apiVersion: v1
kind: Service
metadata:
  name: springboot-mongodb-service
  namespace: test
spec:
  selector:
    app: springboot-mongodb
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
     